const classNames = {
	opaqueBg: [
		"fixed",
		"inset-0",
		"bg-gray-500",
		"bg-opacity-75",
		"transition-opacity,",
	],
	flexContainer: [
		"flex",
		"min-h-full",
		"items-end",
		"justify-center",
		"p-4",
		"text-center",
		"sm:items-center",
		"sm:p-0",
	],
	positionRelative: [
		"relative",
		"transform",
		"overflow-hidden",
		"rounded-lg",
		"bg-white",
		"text-left",
		"shadow-xl",
		"transition-all",
		"sm:my-8",
		"sm:w-full",
		"sm:max-w-lg",
	],
	itemsCenter: [
		"mx-auto",
		"flex",
		"h-12",
		"w-12",
		"flex-shrink-0",
		"items-center",
		"justify-center",
		"rounded-full",
		"bg-blue-200",
		"sm:mx-0",
		"sm:h-10",
		"sm:w-10",
	],
	activateBtn: [
		"inline-flex",
		"w-full",
		"justify-center",
		"rounded-md",
		"bg-blue-600",
		"px-3",
		"py-2",
		"text-sm",
		"font-semibold",
		"text-white",
		"shadow-sm",
		"hover:bg-blue-500",
		"sm:ml-3",
		"sm:w-auto",
	],
	cancelBtn: [
		"mt-3",
		"inline-flex",
		"w-full",
		"justify-center",
		"rounded-md",
		"bg-white",
		"px-3",
		"py-2",
		"text-sm",
		"font-semibold",
		"text-gray-900",
		"shadow-sm",
		"ring-1",
		"ring-inset",
		"ring-gray-300",
		"hover:bg-gray-50",
		"sm:mt-0",
		"sm:w-auto",
	],
}

export default classNames
